name: Bug Report
description: Report a bug or issue with Rails Error Dashboard
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: If applicable, add logs or screenshots to help explain your problem
      placeholder: Paste logs here or drag and drop screenshots...

  - type: input
    id: gem-version
    attributes:
      label: Gem Version
      description: What version of rails_error_dashboard are you using?
      placeholder: "0.1.27"
    validations:
      required: true

  - type: input
    id: rails-version
    attributes:
      label: Rails Version
      description: What version of Rails are you using?
      placeholder: "7.1.0"
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: Ruby Version
      description: What version of Ruby are you using?
      placeholder: "3.2.0"
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database
      description: What database are you using?
      options:
        - PostgreSQL
        - MySQL
        - SQLite
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other relevant information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I can reliably reproduce this issue
          required: false
